### ISSUE TITLE
请兼容SSR

### ISSUE THREAD

**Issue by hnliyuan** [infeng/react-viewer#70]
组件中存在的自执行代码会在ssr时报错。
` ReferenceError: document is not defined
    at new Viewer (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-viewer/dist/index.js:230:35)
    at processChild (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-dom/cjs/react-dom-server.node.development.js:2750:14)
    at resolve (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
    at ReactDOMServerRenderer.render (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
    at ReactDOMServerRenderer.read (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToString (/Users/lc/WebstormProjects/m-crossborder-mall/node_modules/react-dom/cjs/react-dom-server.node.development.js:3526:27)
    at /Users/lc/WebstormProjects/m-crossborder-mall/src/server.tsx:140:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by infeng** [comment]
谢谢反馈，我看下怎么弄

**Comment by infeng** [comment]
Fixed in `v2.10.0`

**Comment by panyifei** [comment]
ssr还是有问题，3.x最新版本

**Comment by infeng** [comment]
@panyifei 感觉反馈，尽快修复

**Comment by infeng** [comment]
`v3.2.0` ssr works.
